version: "2.4"
services:
  redis:
    image: redis:latest
    container_name: sys_redis
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nfs/zsd_server/docker/data/redis:/data
    ports:
      - "6379:6379"
    logging:
      options:
        max-size: "10m"

  mongo:
    image: mongo:6
    container_name: sys_mongo
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nfs/zsd_server/docker/data/mongo:/data
      - /mnt/nfs/zsd_server/docker/data/mongo/db:/data/db
      - /mnt/nfs/zsd_server/docker/data/mongo/configdb:/data/configdb
    ports:
      - "27017:27017"
    logging:
      options:
        max-size: "10m"

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: sys_rabbitmq
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nfs/zsd_server/docker/data/rabbitmq:/var/lib/rabbitmq
      - /mnt/nfs/zsd_server/docker/data/rabbitmq/conf.d:/etc/rabbitmq/conf.d
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      options:
        max-size: "10m"

#   mosquitto:
#     image: eclipse-mosquitto
#     container_name: sys_mosquitto
#     volumes:
#       - /etc/timezone:/etc/timezone:ro
#       - /etc/localtime:/etc/localtime:ro
#     ports:
#       - 1883:1883
#       - 9001:9001
#     logging:
#       options:
#         max-size: "10m"

  watchtower:
    image: containrrr/watchtower
    container_name: sys_watchtower
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    logging:
      options:
        max-size: "10m"
