version: "3.7"

services:
 kms-server:
  image: luodaoyi/kms-server:latest
  container_name: "kms-server"
  volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  ports:
    - 1688:1688
  restart: always
  logging:
      options:
        max-size: "10m"
