version: "3.7"

services:
 kms-server:
  image: luodaoyi/kms-server:latest
  container_name: "kms-server"
  volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  ports:
    - 1688:1688
  restart: always
  logging:
      options:
        max-size: "10m"
# Windows 10/Windows 11 专业版
# 以管理员身份打开命令提示符窗口，然后输入以下命令：
# slmgr.vbs /upk
# slmgr /ipk W269N-WFGWX-YVC9B-4J6C9-T83GX
# slmgr /skms kms.03k.org
# slmgr /ato

 bz_chan_server:
  image: zhangsheng377/bz_chan_image:latest
  container_name: bz_chan_server
  restart: always
  ports:
    - "22226:22226"
  environment:
    MONGODB_HOST: '192.168.10.5'
    MONGODB_PORT: 27017
    REDIS_HOST: '192.168.10.5'
    REDIS_PORT: 6379
    PORT: 22226
    - TZ=Asia/Shanghai
  logging:
    options:
      max-size: "10m"
  entrypoint:
    - /bin/bash
    - docker_cmd_server.sh
