version: "3.7"

services:
 kms-server:
  image: luodaoyi/kms-server:latest
  container_name: "kms-server"
  volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  ports:
    - 1688:1688
  restart: always
  logging:
      options:
        max-size: "10m"
# Windows 10/Windows 11 专业版
# 以管理员身份打开命令提示符窗口，然后输入以下命令：
# slmgr.vbs /upk
# slmgr /ipk W269N-WFGWX-YVC9B-4J6C9-T83GX
# slmgr /skms kms.03k.org
# slmgr /ato
