version: "3"
services:
#   nas-tools:
#     image: mhmzx/nas-tools-enhanced:latest
#     ports:
#       - 3000:3000        # 默认的webui控制端口
#     volumes:
#       - /mnt/nfs/zsd_server/docker/data/nas-tools/config:/config   # 冒号左边请修改为你想保存配置的路径
#       - /mnt/nfs/download:/download   # 媒体目录，多个目录需要分别映射进来，需要满足配置文件说明中的要求
# #       - /etc/timezone:/etc/timezone:ro
# #       - /etc/localtime:/etc/localtime:ro
#     environment: 
#       - PUID=1000    # 想切换为哪个用户来运行程序，该用户的uid
#       - PGID=1000    # 想切换为哪个用户来运行程序，该用户的gid
#       - UMASK=000 # 掩码权限，默认000，可以考虑设置为022
#       - NASTOOL_AUTO_UPDATE=true  # 如需在启动容器时自动升级程程序请设置为true
#       - NASTOOL_CN_UPDATE=true # 如果开启了容器启动自动升级程序，并且网络不太友好时，可以设置为true，会使用国内源进行软件更新
#      #- REPO_URL=https://ghproxy.com/https://github.com/jxxghp/nas-tools.git  # 当你访问github网络很差时，可以考虑解释本行注释
#     restart: always
#     network_mode: bridge
#     hostname: nas-tools
#     container_name: nas-tools
#     logging:
#       options:
#         max-size: "10m"
  
  emby:
    image: emby/embyserver
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - /mnt/nfs/zsd_server/docker/data/emby/config:/config
      - /mnt/nfs/download:/download   # 媒体目录，多个目录需要分别映射进来，需要满足配置文件说明中的要求
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UID=0
      - GID=0
#       - GIDLIST=1000
      - GIDLIST=2
    group_add:
      - "109" # Change this to match your "render" host group id and remove this comment
    devices:
#       - /dev/dri/renderD128:/dev/dri/renderD128  # VMware SVGA II Adapter
      - /dev/dri/renderD129:/dev/dri/renderD129  # Intel Corporation UHD Graphics 620 (rev 07)
    restart: unless-stopped
